baseURL = "https://rayes0.github.io"
languageCode = "en-ca"
title = "rayes"
theme = "tex-like"

# allows getting info like last modified date from git
enableGitInfo = true

# Pagination
paginate = 5  # How many posts to show per category on homepage (Hugo's builtin paginator)
[params]
	paginateList = 15  # How many posts to show per category on list pages

[author]
	name = "rayes"
	description = ""

# markup settings tweaked for this theme
# recommended that you keep these except for commented lines
[markup]
	[markup.highlight]
		style = "solarized-light"  # set to whatever you prefer
	[markup.tableOfContents]
		startLevel = 1
		ordered = true
	[markup.goldmark.renderer]
		unsafe = true  # allows raw html in markdown files, keep if you need it

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]  # set priority for lastmod of post

[menu]
  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1
  [[menu.main]]
    identifier = "blog"
    name       = "Posts"
    url        = "blog/"
    weight     = 2
  [[menu.main]]
    identifier = "meta"
    name       = "Meta"
    url        = "meta/"
    weight     = 3
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    weight     = 4

[taxonomies]
	status = "status"
  tags = "tags"
  category = "categories"
