baseURL = "https://rayes0.github.io" # don't add trailing slash
languageCode = "en-ca"
title = "rayes"
theme = "tex-like"
enableRobotsTXT = true
enableGitInfo = true

# Pagination
paginate = 3

[params]
  paginateList = 15
  source = "https://github.com/rayes0/blog/"
  license = "https://creativecommons.org/licenses/by/4.0/"
  licenseName = "license"
  showCopyright = false
  showLicense = true
  # poweredBy = [ ["Hugo", "https://gohugo.io/"],
  #               ["ox-hugo", "https://ox-hugo.scripter.co/"],
  #               ["Org mode", "https://orgmode.org/"] ]
  mainSections = ['blog']
  noList = ['About', 'Meta']

[author]
	name = "rayes"
	description = ""

[markup]
	[markup.highlight]
		style = "solarized-light"
	[markup.tableOfContents]
		startLevel = 1
		ordered = true
	[markup.goldmark.renderer]
		unsafe = true

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[menu]
  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1
  [[menu.main]]
    identifier = "blog"
    name       = "Writing"
    url        = "blog/"
    weight     = 2
  [[menu.main]]
    identifier = "meta"
    name       = "Meta"
    url        = "meta/"
    weight     = 3
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    weight     = 4

[taxonomies]
	status = "status"
  tags = "tags"
  category = "categories"
